# Welcome to Jekyll!!!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Commands

# serve local:
# bash -c "jekyll serve --future --drafts --livereload"

# build for development:
# bash -c "jekyll build --future"

# build for production:
# bash -c "JEKYLL_ENV=production jekyll build"
# bash -c "JEKYLL_ENV=production jekyll build"; .\push.ps1


# Install everything for windows 10

# - git, code, ...
# - Windows Features: +Windows-Subsystem for linux
# - Windows Store: +Ubuntu ( https://www.microsoft.com/store/productId/9NBLGGH4MSV6 )
# - start ubuntu, wait for initial setup, follow user setup
# - update packages: sudo apt-get update -y && sudo apt-get upgrade -y
# - install jekyll https://jekyllrb.com/docs/windows/
# - gem install jekyll fails? try 
#      sudo apt install clang make ruby-dev libffi-dev
#      sudo gem install ffi
# - winscp is needed for pushing to production: choco install winscp
# - create winscp stored session

title: Fabse.net - Elektronik, Heimkino, Heimwerken
email: fabse@fabse.net
lang: de
author: Fabian Wetzel
port: 4002
description: > # this means to ignore newlines until "baseurl:"
  Dieser Blog begleitet textuell meinen YouTube-Kanal und bietet weitere Inhalte sowie aktualisierte Inhalte, sofern notwendig.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fabse.net" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d.%m.%Y"

permalink: /:categories/:year/:month/:day/:title/

#google_analytics: UA-34726227-3

disqus:
  shortname: fabsenet

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier

jekyll-minifier:
  exclude: 'feed.xml'
  remove_intertag_spaces: true
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.txt
  - push.ps1

include:
  - .well-known
